import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

/**
 * This edge function serves as a bridge between your app and n8n workflows.
 * 
 * It can be called by n8n to:
 * 1. Fetch user tasks for daily reminders
 * 2. Trigger scheduled automations
 * 
 * Configure your n8n workflow to call this endpoint with the appropriate action.
 */

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { action, userId, data } = await req.json();
    
    console.log(`n8n webhook called: action=${action}, userId=${userId}`);

    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    switch (action) {
      case 'get-user-tasks': {
        // Fetch tasks for a specific user (used by n8n for daily reminders)
        const { data: tasks, error } = await supabase
          .from('tasks')
          .select('*')
          .eq('user_id', userId)
          .neq('status', 'done')
          .order('priority', { ascending: false });
        
        if (error) throw error;
        
        return new Response(
          JSON.stringify({ tasks }),
          { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      }
      
      case 'get-users-for-reminders': {
        // Get all users who have reminder_time set (for n8n cron job)
        const { data: profiles, error } = await supabase
          .from('profiles')
          .select('user_id, name, email, reminder_time')
          .not('reminder_time', 'is', null);
        
        if (error) throw error;
        
        return new Response(
          JSON.stringify({ users: profiles }),
          { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      }
      
      case 'save-plan': {
        // Save a plan generated by n8n workflow
        const { error } = await supabase
          .from('plans')
          .insert({
            user_id: userId,
            generated_text: data.planText,
            source_task_ids: data.taskIds || []
          });
        
        if (error) throw error;
        
        return new Response(
          JSON.stringify({ success: true }),
          { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      }
      
      default:
        return new Response(
          JSON.stringify({ error: `Unknown action: ${action}` }),
          { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
    }
  } catch (error) {
    console.error('Error in n8n-webhook:', error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : 'Unknown error' }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});